name: Flutter Build(PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.47.0'

      - run: flutter pub get
      - run: flutter build windows

      - uses: actions/upload-artifact@v7
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v7
        with:
          name: web-build
          path: build/web
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.47.0'

      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi

      - uses: actions/upload-artifact@v7
        with:
          name: android-arm-v7a-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      
      - uses: actions/upload-artifact@v7
        with:
          name: android-arm-v8a-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      
      - uses: actions/upload-artifact@v7
        with:
          name: android-x86_64-apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
